modLoader="javafml"
loaderVersion="[4,)"
license="All rights reserved"

[[mods]]
modId="lwlwlwl_mech_"
version="1.0.0"
displayName="Lwlwlwlmech"
logoFile="logo.png"
credits=""
authors="mofus"
description='''
A mod that adds:
- Mech Creation Station
- Nautilus Submarine
'''

[[dependencies.lwlwlwl_mech_]]
modId="minecraft"
mandatory=true
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"

[[dependencies.lwlwlwl_mech_]]
modId="neoforge"
mandatory=true
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.lwlwlwl_mech_]]
modId="geckolib"
mandatory=true
versionRange="[4.8,)"
ordering="NONE"
side="BOTH"